name: Build and Test Memory Leak Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile heapmemleak.cpp
      run: |
        cl.exe /EHsc /Fe:memoryleak.exe heapmemleak.cpp

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: memoryleak
        path: memoryleak.exe
        retention-days: 180
