name: Build and Test Memory Leak Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile heapmemleak.c++
      run: |
        cl.exe /EHsc /Fe:memoryleak.exe heapmemleak.c++
      
    - name: Upload compiled executable
      uses: actions/upload-artifact@v3
      with:
        name: memoryleak
        path: memoryleak.exe

  test:
    needs: build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download compiled executable
      uses: actions/download-artifact@v3
      with:
        name: memoryleak
    
    - name: Run Atomic Test
      run: |
        .\memoryleak.exe
      timeout-minutes: 2
    
    - name: Check for HeapLeakDetection registry artifact
      run: |
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\HeapLeakDetection"
        if (Test-Path $regPath) {
          Write-Output "HeapLeakDetection registry key found. Test likely successful."
          Get-ItemProperty $regPath
        } else {
          Write-Output "HeapLeakDetection registry key not found. Test may have failed or needs more time."
          exit 1
        }
